update CI

diff --git a/.github/workflows/cleanup.yml b/.github/workflows/cleanup.yml
--- a/.github/workflows/cleanup.yml
+++ b/.github/workflows/cleanup.yml
@@ -1,11 +1,9 @@
 name: cleanup caches by a branch
-on:
-  pull_request:
-    types:
-      - closed
-
+on: delete
+  
 jobs:
   cleanup:
+    if: github.event.ref_type == 'branch'
     runs-on: ubuntu-latest
     steps:      
       - name: Cleanup
@@ -13,17 +11,24 @@ jobs:
           gh extension install actions/gh-actions-cache
           
           echo "Fetching list of cache key"
-          cacheKeysForPR=$(gh actions-cache list -R "$REPO" -B "$BRANCH" | cut -f 1 )
+          cacheKeysForPR=$(gh actions-cache list -R "${REPO}" -B "${BRANCH}" -L 100 | cut -f 1 )
+          while test -n "${cacheKeysForPR}"
+          do 
+            ## Setting this to not fail the workflow while deleting cache keys. 
+            set +e
+            echo "Deleting caches..."
+            for cacheKey in ${cacheKeysForPR}
+            do
+                gh actions-cache delete "${cacheKey}" -R "${REPO}" -B "${BRANCH}" --confirm
+            done
 
-          ## Setting this to not fail the workflow while deleting cache keys. 
-          set +e
-          echo "Deleting caches..."
-          for cacheKey in $cacheKeysForPR
-          do
-              gh actions-cache delete "$cacheKey" -R "$REPO" -B "$BRANCH" --confirm
+            ## Setting this to fail the workflow while fetching cache keys. 
+            set -e
+            cacheKeysForPR=$(gh actions-cache list -R "${REPO}" -B "${BRANCH}" -L 100 | cut -f 1 )
+
           done
           echo "Done"
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           REPO: ${{ github.repository }}
-          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
+          BRANCH: ${{ github.event.ref }}
